name: "test-local"
on:
  pull_request:
  push:
    branches:
      - master
      - 'releases/*'

jobs:
  test:
    name: Action Test
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]


    steps:
      - uses: actions/checkout@v1

      - name: Elm setup
        uses: ./
        with:
          elm-version: 0.19.1

      - name: Elm setup (default version)
        uses: ./

      - name: Elm Home folder
        run: echo $ELM_HOME

      - name: Checking command
        run: |
          elm --help
